import Link from "../components/Link.tsx";
import { PageTitle, Point, Prose, Section } from "../components/Prose.tsx";

const LINK =
  "text-sky-800 underline focus-visible:outline-2 focus-visible:outline-offset-2 " +
  "focus-visible:outline-sky-700";

export default function AboutPage() {
  return (
    <div>
      <PageTitle>About ClearSkies</PageTitle>

      <Prose>
        <p>
          ClearSkies joins EPA compliance records, toxic release inventories, modeled air
          toxics exposure, measured air quality and census demographics into a single
          burden score for every hexagon in Louisiana. Click one and it shows why it
          scored the way it did, which facilities contributed, and how confident the
          score is.
        </p>
        <p>
          The data proving that polluting industry is unevenly distributed is public, and
          it is scattered across several government databases with different formats and
          quirks. Joining it up is most of the work.
        </p>
      </Prose>

      <Section title="Please read these before using it">
        <Point label="This is not legal advice.">
          Nothing on this site is legal advice, and nothing generated by it should be
          filed, sent or published without review by someone qualified to do so.
        </Point>
        <Point label="A score is not an accusation.">
          A high burden score describes a pattern in public data. It is not a finding of
          wrongdoing by any facility or operator, and facilities operating fully within
          their permits contribute to burden scores.
        </Point>
        <Point label="Drafts are drafts.">
          Every generated document is labelled as requiring human review. There is no
          send button and no publish path anywhere in this system.
        </Point>
        <Point label="A low score is not a clean bill of health.">
          It can mean low burden, or it can mean the indicators that would have caught
          the burden are missing. Read the confidence value alongside the score.
        </Point>
      </Section>

      <Section title="Scope">
        <p>
          Louisiana only, air pollution and industrial facility burden only. Percentiles
          are Louisiana percentiles. Water quality, soil contamination, drinking water,
          pesticides, traffic and health outcomes are all out of scope for this version,
          and the methodology records where each would belong.
        </p>
        <p>
          Also out of scope: national coverage, user accounts, and any automatic sending
          or publishing.
        </p>
      </Section>

      <Section title="Data and licence">
        <p>
          Every upstream dataset is US public-domain government data. The code is MIT
          licensed. The{" "}
          <Link to="/provenance" className={LINK}>
            sources page
          </Link>{" "}
          records each source, when it was last fetched and its known gaps;{" "}
          <Link to="/methodology" className={LINK}>
            the methodology
          </Link>{" "}
          covers how the score is built, and{" "}
          <Link to="/model-card" className={LINK}>
            the model card
          </Link>{" "}
          covers the drafting assistant.
        </p>
      </Section>
    </div>
  );
}
